### ISSUE TITLE
ImportError on startup

### ISSUE THREAD

**Issue by freswa** [pklaus/labelweb#2]
Getting this while executing labelweb:
```
% ./labelweb                    
Bottle v0.12.13 server starting up (using CherryPyServer())...
Listening on http://127.0.0.1:7777/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "./labelweb", line 17, in <module>
    LabelWeb().run(debug=args.debug, server=server, port=args.port)
  File "/usr/lib/python3.6/site-packages/bottle.py", line 755, in run
    run(self, **kwargs)
  File "/usr/lib/python3.6/site-packages/bottle.py", line 3127, in run
    server.run(app)
  File "/usr/lib/python3.6/site-packages/bottle.py", line 2787, in run
    from cherrypy import wsgiserver
ImportError: cannot import name 'wsgiserver'
```
Browser isn't even open. So no interaction besides starting the executable.

**Comment by christianlupus** [comment]
I have the very same problem on Archlinux.

**Comment by christianlupus** [comment]
@freswa Could you please try something out. I was able to get it running using the command `./labelweb --debug`. Can you confirm this?
